### ISSUE TITLE
Composer como Gerenciador de Dependências

### ISSUE THREAD

**Issue by wandersonwhcr** [lu2cas/lu2cas#1]
Utilize o Composer para efetuar o gerenciamento de dependências, como o PHPMailer.

https://packagist.org/packages/phpmailer/phpmailer

**Comment by wandersonwhcr** [comment]
Também podes utilizar o Bower para instalar as dependências de _frontend_.

**Comment by lu2cas** [comment]
Foram criados os arquivos de configuração do Composer; O pacote phpmailer/phpmailer já foi instalado a partir do mesmo.

**Comment by wandersonwhcr** [comment]
Agora tu podes ignorar o `vendor` e versionar o `composer.lock`.

O arquivo `composer.lock` existe para informar qual a versão precisa deve ser utilizada nos ambientes. Seu versionamento deve ser feito para que todo mundo instale a mesma versão e para que não tenha aquele problema do "na minha máquina funciona".

Isto é bom inclusive nos testes, pois, quando executados, utilizam as mesmas versões dos ambientes de desenvolvimento e produção.

**Comment by lu2cas** [comment]
- Arquivo `composer.lock` versionado;
- Diretório `vendor` removido e ignorado do versionamento.

**Comment by lu2cas** [comment]
Também criei o arquivo de configuração do Bower para gerenciamento de dependências client-side; Os pacotes `jquery` e `jquery-ui` foram instalados a partir do Bower.

**Comment by wandersonwhcr** [comment]
Dica: se tu precisar instalar as dependências em local específico, como `assets/` e não `bower_components/`, tu pode colocar um arquivo com o nome `.bowerrc` com o conteúdo:

```json
{
    "directory": "assets"
}
```
